### PR TITLE
Android improvements

### PR DESCRIPTION
**Pull request by fjgal**
Addresses proposal in issue #3 

* disconnect method implementation
* WPA2 and WPA3 being mutually exclusive
* support connection on API < 29 without location permission

### CODE REVIEW

**Comment by vipero07** [comment]
looks good to me, thanks for the pull

**Comment by vipero07** [comment]
I may change is wpa2 and iswpa3 to two unique methods like connect to wpa2 / connect to wpa3, but for now this is more than sufficient.

**Comment by fjgal** [comment]
>I may change is wpa2 and iswpa3 to two unique methods like connect to wpa2 / connect to wpa3, but for now this is more than sufficient.

My intention was to keep it backward compatible (in the case of WPA2) - and also symmetric with WEP. If you prefer to have different methods that works too, it is a breaking change but that early in the development it is totally acceptable.

**Comment by vipero07** [comment]
That's my thoughts precisely. As its still version ~0.0

It may be wonky with iOS considerations though so I haven't really come to any conclusion.

**Pull request merged**
